"""Añadir campos background_image y background_video al modelo User

Revision ID: 51ac2ca55220
Revises: 484d36677857
Create Date: 2024-11-26 02:31:03.645779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ac2ca55220'
down_revision = '484d36677857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('background_image', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('background_video', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('background_video')
        batch_op.drop_column('background_image')

    # ### end Alembic commands ###
