"""Borrar description userlink

Revision ID: 55782a0141f3
Revises: 9a6f7c53a171
Create Date: 2024-11-28 12:58:11.484519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55782a0141f3'
down_revision = '9a6f7c53a171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_link', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
