"""Añadir campo background_type al modelo User

Revision ID: 76c4ad3d9dc0
Revises: 92f1a35a091b
Create Date: 2024-11-26 02:59:05.231010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c4ad3d9dc0'
down_revision = '92f1a35a091b'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Agregar la columna con un valor predeterminado 'image'
        batch_op.add_column(
            sa.Column('background_type', sa.String(length=10), nullable=False, server_default='image')
        )
        # Opcional: Remover el server_default si no deseas mantenerlo
        # batch_op.alter_column('background_type', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('background_type')

    # ### end Alembic commands ###
