"""Add ClickLog model

Revision ID: 97980ed47ae3
Revises: 55782a0141f3
Create Date: 2024-11-28 13:39:39.857492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97980ed47ae3'
down_revision = '55782a0141f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['user_link.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('click_log')
    # ### end Alembic commands ###
