"""Agregar campo clicks a UserLink

Revision ID: 9a6f7c53a171
Revises: 6ec382f0a40a
Create Date: 2024-11-27 23:21:05.817576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a6f7c53a171'
down_revision = '6ec382f0a40a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clicks', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_link', schema=None) as batch_op:
        batch_op.drop_column('clicks')

    # ### end Alembic commands ###
