"""product upgraded

Revision ID: c9ffd112ba02
Revises: 4e0a44c9d9f3
Create Date: 2024-12-03 12:27:05.099238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9ffd112ba02'
down_revision = '4e0a44c9d9f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False, server_default='NFC'))
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('stock')
        batch_op.drop_column('discount')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
